version: "3.9"
services:
  # postgres database
  uag-db:
    container_name: uag-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  # Spring Application
  uag-service:
    container_name: uag-service
    depends_on:
      - uag-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://uag-db:5432/postgres?user=postgres&password=postgres
    expose:
      - "8081:8080" # exposing a different port, so it's possible to run it both locally and in the container
